### PR TITLE
Jentjr patch 1

### LINKED ISSUE #2: Drop `libgfortran`
Appears the recipe is [explicitly listing `libgfortran` in `host`]( https://github.com/conda-forge/timml-feedstock/blob/a43825233417dab2c1898e6c1be4df66cf72ba64/recipe/meta.yaml#L26 ) and [`run`]( https://github.com/conda-forge/timml-feedstock/blob/a43825233417dab2c1898e6c1be4df66cf72ba64/recipe/meta.yaml#L36 ). However this is not needed as the `fortran` compilers list [`libgfortran` in `run_exports`]( https://github.com/conda-forge/toolchain-feedstock/blob/ca83bdace0009769bea574a9fdbde44183ecb825/recipe/meta.yaml#L44-L46 ) for [both of them]( https://github.com/AnacondaRecipes/aggregate/blob/72bfe3466a669c22fbf7316e076377395cdc61f8/gfortran-feedstock/recipe/meta.yaml#L60-L62 ). So they will automatically be added at run time for any package using them. Not to mention the compilers require these libraries themselves. As a result, `libgfortran` can and should be dropped from the recipe.

### PR DESCRIPTION
**Pull request by jentjr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #2 

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by jakirkham** [comment]
FYI pushing to a branch on the feedstock will deploy packages even before an associated PR is merged. Best to use a fork for this sort of thing in the future.

ref: https://conda-forge.org/docs/conda-forge_gotchas.html#using-a-fork-vs-a-branch-when-updating-a-recipe

**Comment by jakirkham** [comment]
Looks like the build that failed only failed to upload. The build itself seemed to go through ok.

**Comment by jakirkham** [comment]
Should add feel free to merge when this passes. Looks right and looks like it is working.

**Comment by jentjr** [comment]
Thanks

**Pull request merged**
